# Generated by Django 4.0.2 on 2022-06-06 02:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('votes', models.BigIntegerField(default=0)),
                ('rating', models.FloatField(default=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1win', models.BooleanField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('item1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_item', to='vote.item')),
                ('item2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_item', to='vote.item')),
            ],
        ),
    ]
