# Generated by Django 4.0.2 on 2022-10-26 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_item_gender_alter_vote_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='college',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vote.college'),
            preserve_default=False,
        ),
    ]
